[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:Mi)/$swap_total.eng(w:3,u:B,p:Mi)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1
format = " $icon $barchart $utilization "
format_alt = " $icon $frequency{ $boost|} "
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "sound"
driver = "auto"
device = 'hw:0,0'
format = " $icon { $volume|} "

[[block]]
block = "battery"
format = " $icon $percentage "

[[block]]
block = "time"
format = " $icon $timestamp.datetime() "
timezone = "Europe/Amsterdam"
interval = 10
