#+title: tmux configuration
#+property: header-args :tangle .tmux.conf

* Table of contents :toc:
- [[#tmux-configuration][tmux configuration]]
  - [[#plugins][Plugins]]
  - [[#theming][Theming]]
  - [[#basic][Basic]]
  - [[#window][Window]]
  - [[#navigation][Navigation]]
  - [[#initialize-tpm][Initialize =tpm=]]

* tmux configuration
** Plugins
Make sure that the tmux plugin manager =tpm= is installed, see for instructions https://github.com/tmux-plugins/tpm

#+begin_src conf
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
#+end_src

** Theming
Install the =dracula= theme https://draculatheme.com/tmux and configure it.

#+begin_src conf
set -g @plugin 'dracula/tmux'
# available plugins: battery, cpu-usage, git, gpu-usage, ram-usage, network, network-bandwidth, network-ping, weather, time
set -g @dracula-plugins 'cpu-usage git ram-usage time'
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-fahrenheit false
set -g @dracula-show-location false
#+end_src

** Basic
*** Reset the prefix for the keybindings
Set the prefix to =Ctrl-a= and unbind the original prefix.

#+begin_src conf
set -g prefix C-a
unbind C-b
#+end_src

*** Command delay
#+begin_src conf
set -s escape-time 1
#+end_src

*** Base index
Windows and panes can be addresses by using an index, normally it starts with =0=, this option sets it to =1=.

#+begin_src conf
set -g base-index 1
setw -g pane-base-index 1
#+end_src

*** Reload configuration
#+begin_src conf
bind r source-file ~/.tmux.conf |; display "Reloaded"
#+end_src

*** Passthrough C-a
Ensure that C-a is send to other apps, C-a has to be invoked twice to let another app receive the keybinding

#+begin_src conf
bind C-a send-prefix
#+end_src

*** Disable mouse
#+begin_src conf
set -g mouse off
#+end_src

*** Clipboard
Use =xclip= to copy buffer to system clipboard.

#+begin_src conf
bind C-c run 'tmux safe-buffer- | xclip -sel clip -i'
#+end_src

** Window
*** Split
Split window/pane with =|= and =-=.

#+begin_src conf
bind | split-window -h
bind - split-window -v
#+end_src

*** Cycle
Alternative cycle windows next/previous.

#+begin_src conf
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
#+end_src

** Navigation
*** Movement
Pane movement *Vim* style.

#+begin_src conf
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
#+end_src

*** Resize
Pane resizing *Vim* style. The ~-r~ argument makes it easier to repeat the command.

#+begin_src conf
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
#+end_src

*** Buffer
Use *Escape* to enter =copy mode=.

#+begin_src conf
bind Escape copy-mode
#+end_src

Use =vi= keys to navigate within a buffer.

#+begin_src conf
setw -g mode-keys vi
#+end_src

Use =v= and =y= to copy and paste text

#+begin_src conf
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection
unbind p
bind p paste-buffer
#+end_src

** Initialize =tpm=
This must be done at the bottom of the configuration file.

#+begin_src conf
run '~/.tmux/plugins/tpm/tpm'
#+end_src
